### ISSUE TITLE
ARM Linux (Manjaro XFCE, Raspberry PI 4B) – No title bar with buttons

### ISSUE THREAD

**Issue by SpacingBat3** [NeverDecaf/discord-chrome-app#4]
When launching discord app, title bar won't render:
![Przechwycenie obrazu ekranu_2020-05-20_10-52-33](https://user-images.githubusercontent.com/57194920/82426747-883ab500-9a88-11ea-857f-9f0c2645e58b.png)
For other XFCE distros, I launched it earlier on Xubuntu X86. However I didn't check if it's working on Manjaro for X86 processors. Also, I don't know it's behaviour on other desktop environments or OS'es for RPI.
Any help with that?

**Comment by NeverDecaf** [comment]
Can you check the result of [getPlatformInfo](https://developer.chrome.com/extensions/runtime#method-getPlatformInfo) by running `chrome.runtime.getPlatformInfo(function(r) {console.log(r)})` in your browser's console? The titlebar css is only applied if the os value is one of `win,linux,mac,openbsd`.

**Comment by SpacingBat3** [comment]
As the output it prints "undefined":
![image](https://user-images.githubusercontent.com/57194920/82496941-c7e7b800-9aed-11ea-89ae-69b4876d4e6f.png)

To open console I went to chrome://extension and use console as one of the background scripts. Is that correct?

For additional info, I'm using Chromium, not Chrome. Just in case if that's important (even if I'm sure it's not really for now).

Anyway, thanks for quick answer.

**Comment by NeverDecaf** [comment]
Did not account for platformInfo being undefined, let me know if 1.2.5 fixes this issue for you.

**Comment by SpacingBat3** [comment]
Now everything seems fine, thank you for your fast response!
![Przechwycenie obrazu ekranu_2020-05-21_12-15-32](https://user-images.githubusercontent.com/57194920/82549209-dcaf6480-9b5c-11ea-991b-58a23375d1dd.png)
Closing an issue.
