### ISSUE TITLE
"Flashing" Discord name on RPiOS

### ISSUE THREAD

**Issue by SrIzan10** [NeverDecaf/discord-chrome-app#5]
Hi!
I have a problem on the RPiOS running on a 3b+.
When you don't select the app the name in the taskbar is like "flashing"
Well, only look at the video:
(Github doesn't support videos, so here is the link)
[https://drive.google.com/file/d/1-z0WqfuiCuC-LCeqDabxbFaYRr9PBisG/view?usp=sharing](url)
Thank you.

**Comment by NeverDecaf** [comment]
Do you have any unread messages? This might be the standard behavior for [drawAttention](https://developer.chrome.com/apps/app_window#type-AppWindow) on your OS. If this is the case you can do one of the following:
1. Read your unread messages.
2. [Edit the extension](https://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions) and remove the call to `drawAttention` in `embed.js`; specifically, line 53: `curwindow.drawAttention();`
3. Try the [PWA](https://github.com/NeverDecaf/discord-PWA) version which has an option to disable drawAttention (set highlight to `don't highlight`) in the extension's options.

**Comment by SrIzan10** [comment]
Ok. Now. Thanks!
