### ISSUE TITLE
CRX_REQUIRED_PROOF_MISSING

### ISSUE THREAD

**Issue by tatsumasagc** [NeverDecaf/discord-chrome-app#6]
When I try to load discord-chrome-app.crx into Chromium Version 78.0.3904.108 (Official Build) Built on Raspbian, Running on (32-bit) I get "Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'."

**Comment by NeverDecaf** [comment]
Did you try the workaround in the readme?
